### ISSUE TITLE
ENCODING_UTF8_BOM / NOBOM inversion

### ISSUE THREAD

**Issue by tothpaul** [MichaelDemidov/DelphiZXingQRCodeEx#3]
Hello,

in TEncoder.Append8BitBytes the BOM is added for EncodeOptions = 4 while ENCODING_UTF8_BOM = 5

you should use ENCODING_xxx constants in TEncoder.ChooseMode() 

```
  if EncodeOptions = ENCODING_AUTO then 
   ...
    if AllISO then
    begin
      Result := qmByte;
      EncodeOptions := ENCODING_8BIT;
    end else
    begin
      Result := qmByte;
      EncodeOptions := ENCODING_UTF8_NOBOM; // or BOM ?
    end;
  end else
    case EncodeOptions of
      ENCODING_NUMERIC     : Result := qmNumeric;
      ENCODING_ALPHANUMERIC: Result := qmAlphanumeric;
    else
      Result := qmByte;
    end;
```
    
and in TEncoder.Append8BitBytes() to avoid the bug :)

  if EncodeOptions = ENCODING_XXX

**Comment by MichaelDemidov** [comment]
Hello, Paul.

Thank you! I'll fix it. (Sorry for the late reply—I had covid.)

**Comment by tothpaul** [comment]
I hope you recover quickly !

**Comment by MichaelDemidov** [comment]
Thank you again!

I fixed this and added a global default encoding setting for non-ISO character instead of the hardcoded ENCODING_UTF8_NOBOM
